# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def dependency_pods

  use_frameworks!

  # Network
  pod 'Alamofire', '~> 5.4.3'
  
  # Reactive
  pod 'RxSwift', '~> 6.2.0'
  pod 'RxCocoa', '~> 6.2.0'
  pod 'RxAlamofire', '~> 6.1.1'
  
  #  Images
  pod 'Kingfisher', '~> 6.3.0'
  
  # Progress Loader
  pod 'PKHUD', '~> 5.3.0'

end

# Main App

target 'Wunderfleet' do
  # Comment the next line if you don't want to use dynamic frameworks
  dependency_pods
  
end

# Tests

target 'WunderfleetTests' do
  inherit! :search_paths
  
  dependency_pods
  
  # Reactive Tests
  pod 'RxTest', '~> 6.2.0'
  pod 'RxBlocking', '~> 6.2.0'
  
end

target 'WunderfleetUITests' do
  # Pods for testing
end
